name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd landingpage_frontend
          git pull origin main
          npm install
          npm run build
          sudo cp -R dist/ /var/www/vhosts/frontend/
          sudo service nginx restart
